name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies and run checks
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        cd app
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check

  unit-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        cd app
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
        cd ..

  static-code-analysis:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install flake8 and run static code analysis
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt     
        pip install flake8
        python -m flake8 app --count --exclude=app/api/urls.py --ignore=F401


  vulnerabilty-scan:
    runs-on: ubuntu-latest
    needs: static-code-analysis

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install bandit and run vulnerabilty scan
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt     
        pip install bandit
        python -m bandit -r app

  build-docker-image:
    runs-on: ubuntu-latest
    needs: vulnerabilty-scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rvvaldes/python-app:latest