name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Migrate database
      run: |
        cd app
        python manage.py makemigrations
        python manage.py migrate
        cd ..

    - name: Persist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: test-results

    - name: Run tests
      run: |
        cd app
        python manage.py test
        cd ..

  post-run:
    needs: unit-test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check if tests failed
      run: |
        if [ ${{ job.status }} != 'Success' ]; then exit 1; fi
